---
resources:
- name: concourse-test-git
  type: git
  icon: github
  source:
    uri: https://github.com/dcc8393410/concourse
- name: curl-data
  type: fly
  source:
    password: {{test-password}}
    username: {{test-password}}
    skip_cert_check: true

jobs:
- name: pipeline-create-one
  public: true
  plan:
  - get: concourse-test-git
    trigger: true
  - task: pipeline-create
    file: tasks/deploy.yaml
- name: pipeline-create-two
  public: true
  plan:
  - get: concourse-test-git
    trigger: true
    passed:
      - pipeline-create-one
  - task: curl-api
    file: tasks/curl.yml
  - put: cloudfoundry
    params:
      manifest: source-code/manifest/concourse-demo-web-manifest.yml
      path: target-web/concourse-demo-web.jar
